### ISSUE TITLE
Move `'use strict';` to top of file

### ISSUE THREAD

**Issue by SimenB** [thlorenz/browserify-ftw#14]
Now `'use strict';` comes underneath all the `require`s.

Loving this module btw!

**Comment by thlorenz** [comment]
Thanks, PR appreciated :)

**Comment by SimenB** [comment]
@thlorenz Hmm, I could probably give it a whack. Could you give a small pointer on where to start?

**Comment by thlorenz** [comment]
Depends on your exact problem, but if your `'use strict'` is inside your `define(...` wrapper then it's to be expected to end up below the `require`s.

You could write a post processor that detects lines like `/^['"]use strict['"];?$/` and moves them to the top.
The user could then turn that on via a flag (should default to off).
So around [here](https://github.com/thlorenz/browserify-ftw/blob/master/browserify-ftw.js#L54) you could inject that post processor.

But in all honesty you could also write a simple `sed` script that goes through all your files after browserify-sed is done and does this.

**Comment by thlorenz** [comment]
Waiting for PR ;)

**Comment by SimenB** [comment]
@thlorenz I'm looking at this now, but I have never used esprima or it's cousins, so I'm lost at where to even start :laughing: 

Would I do something in `get-wrapper`? It'd be right after the header. If `'use strict';`, delete it, set some flag on the module, add it to the top when writing in the `require`s. Right?

**Comment by thlorenz** [comment]
I explained above how this could be done.

You may not even need esprima, a simple line by line parser may work (more detailed explanation above).
